apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qq6uuw8vg-go-gitops
  description: This is GitOps manifest for qq6uuw8vg-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: qq6uuw8vg-go
    backstage.io/kubernetes-id: qq6uuw8vg-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qq6uuw8vg-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qq6uuw8vg-go
